"""add requirements

Revision ID: be6c1a4c0fc8
Revises: 69d4bff6cd80
Create Date: 2026-09-17 14:38:19.325237
"""
from alembic import op
import sqlalchemy as sa


revision = 'be6c1a4c0fc8'
down_revision = '69d4bff6cd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('stable_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria_json', sa.Text(), nullable=False),
    sa.Column('source_references_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stable_id', name='uq_project_requirement_stable_id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_session_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_priority'))
        batch_op.drop_index(batch_op.f('ix_requirements_category'))

    op.drop_table('requirements')
    # ### end Alembic commands ###
